# Generated by Django 5.1.4 on 2024-12-19 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('choice_1', models.CharField(max_length=255)),
                ('choice_2', models.CharField(max_length=255)),
                ('choice_3', models.CharField(max_length=255)),
                ('choice_4', models.CharField(max_length=255)),
                ('correct_choice', models.IntegerField()),
                ('category', models.CharField(choices=[('Science', 'Science'), ('History', 'History'), ('General', 'General Knowledge'), ('Art', 'Art'), ('Sport', 'Sport')], max_length=50)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
